// <auto-generated />
using System;
using Hubert_Michna_w67259.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hubert_Michna_w67259.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20240629083218_Migracja_1")]
    partial class Migracja_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hubert_Michna_w67259.Models.Typ_Wydatku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Typ_Wydatku");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Produkty spożywcze"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Motoryzacja"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Edukacja"
                        });
                });

            modelBuilder.Entity("Hubert_Michna_w67259.Models.Wydatek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Data_Wydatku")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nazwa_Wydatku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Typ_Wydatku_Id")
                        .HasColumnType("int");

                    b.Property<string>("Waluta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wydatek");
                });
#pragma warning restore 612, 618
        }
    }
}
